version: '3'
services:

  #Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dr3
    container_name: app
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - laraveldockerize

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: 
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
      - laraveldockerize

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: birdboard
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
    volumes:
      - ./dockerize/mysql/data:/var/lib/mysql
      - ./dockerize/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - laraveldockerize

#Docker Networks
networks:
  laraveldockerize:
    driver: bridge